# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_commentmodel_likemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='price',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(upload_to=b'instacloneuser_images'),
        ),
    ]
