# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170731_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_text',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
