# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sessionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionModel',
        ),
    ]
