# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_sessionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
